use strict;
use warnings;
#use Devel::Peek;
use Test::More qw/no_plan/;
BEGIN { use_ok('Tsk::Img::Info'); };
use Tsk::Img::Info;
my $o = Tsk::Img::Info->new();
my $path = "testdata/testimage001.001";
my $open_retval = $o->open($path,$TSK_IMG_TYPE_DETECT,0);
ok(defined($open_retval) && !$open_retval,"Tsk::Img::Info::open succeeded");
